language: python
dist: xenial

addons:
  chrome: stable

services:
  - docker

env: # Without this, allow_failures will not work
  global:
    # These env variables are passed to scaffold tests that test the tests themselves
    - SPLINTER_WEBDRIVER=chrome
    - TRAVIS=true
    - DATABASE_URL=postgres://postgres:postgres@localhost:5432/websauna_test

matrix:
    fast_finish: true
    include:
        - python: 3.5
          env:
          - PYTHON_VERSION=python3.5
          - TOXENV=py35
        - python: 3.6
          env:
          - PYTHON_VERSION=python3.6
          - TOXENV=py36
        - python: 3.7
          env:
          - PYTHON_VERSION=python3.7
          - TOXENV=py37
          dist: xenial
          sudo: true
        - python: 3.7
          env:
          - PYTHON_VERSION=python3.7
          - TOXENV=mysql
          - DATABASE_URL=mysql+pymysql://mysql:mysql@localhost:3306/websauna_test
          dist: xenial
          sudo: true
        - python: 3.8-dev
          env:
          - PYTHON_VERSION=python3.8
          - TOXENV=py38
          dist: xenial
          sudo: true
        - python: 3.6
          env:
          - PYTHON_VERSION=python3.6
          - TOXENV=style
    allow_failures:
      - python: 3.8-dev
        env:
        - PYTHON_VERSION=python3.8
        - TOXENV=py38
      - python: 3.7
        env:
        - PYTHON_VERSION=python3.7
        - TOXENV=mysql
        - DATABASE_URL=mysql+pymysql://mysql:mysql@localhost:3306/websauna_test

# http://stackoverflow.com/a/19460794/315168
cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -U pip
  - travis_retry pip install tox coverage-enable-subprocess

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - .travis/setup_chrome.sh

script:
  # https://pypi.python.org/pypi/coverage_enable_subprocess
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
  # Start up docker containers
  - docker-compose -f .travis/docker-compose.yml up -d
  - tox -- --ini=websauna/conf/travis.ini --splinter-webdriver=chrome --splinter-headless=true --debug

after_success:
  - .tox/$TOXENV/bin/codecov
  - .tox/$TOXENV/bin/pip freeze

after_script:
  - docker-compose -f .travis/docker-compose.yml down
