version: '3'
services:
  postgres_db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=websauna_test
    ports:
      - "5432:5432"
  mysql_db:
    image: mysql:8.0
    environment:
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=websauna_test
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
